# GitHub actions workflow.
# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions

name: Build CI

on:
  push:
    branches: [master, gh-actions]
    tags: [v*]
  pull_request:
    types: [opened]
    branches: [master]

jobs:
  Linux:
    strategy:
      matrix:
        os: [ubuntu-latest]
        cc: [gcc, clang]
    runs-on: ${{ matrix.os }}
    env:
      CC: ${{ matrix.cc }}
    steps:
    - uses: actions/checkout@v3
    - run: ./autogen.sh
    - run: ./configure --disable-silent-rules --without-libwrap --without-labeled-networking --without-loadavg
    - run: make
    - run: make install DESTDIR="${PWD}/root/"
    - run: make distcheck

  macOS:
    strategy:
      matrix:
        os: [macos-latest]
        cc: [clang]
    runs-on: ${{ matrix.os }}
    env:
      CC: ${{ matrix.cc }}
    steps:
    - uses: actions/checkout@v3
    - run: brew install autoconf automake libtool
    - run: ./autogen.sh
    - run: ./configure --disable-silent-rules --without-libwrap --without-labeled-networking --without-loadavg
    - run: make
    - run: make install DESTDIR="${PWD}/root/"
